env = Environment(CPPPATH='..')

def boost_lib(s):
    return 'boost_%s-mt' % s

lst_boost_lib = [
    boost_lib('regex'),
    boost_lib('program_options'),
    boost_lib('filesystem'),
    boost_lib('system'),
]

env.Program(
    target    = '_cdd',
    source    = ['main.cpp'],
    LIBS      = ['cdd', ] + lst_boost_lib,
    LIBPATH   = '../cdd',
)
